//
// Generated file, do not edit! Created by nedtool 5.4 from N_PDU.msg.
//

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#ifndef __N_PDU_M_H
#define __N_PDU_M_H

#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0504
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



/**
 * Class generated from <tt>N_PDU.msg:19</tt> by nedtool.
 * <pre>
 * //
 * // TODO generated message class
 * //
 * packet N_PDU
 * {
 *     int NP_id;
 *     int NP_type; //data = 0 ack = 1
 *     int NP_src_address;
 *     int NP_dest_address;
 * }
 * </pre>
 */
class N_PDU : public ::omnetpp::cPacket
{
  protected:
    int NP_id;
    int NP_type;
    int NP_src_address;
    int NP_dest_address;

  private:
    void copy(const N_PDU& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const N_PDU&);

  public:
    N_PDU(const char *name=nullptr, short kind=0);
    N_PDU(const N_PDU& other);
    virtual ~N_PDU();
    N_PDU& operator=(const N_PDU& other);
    virtual N_PDU *dup() const override {return new N_PDU(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual int getNP_id() const;
    virtual void setNP_id(int NP_id);
    virtual int getNP_type() const;
    virtual void setNP_type(int NP_type);
    virtual int getNP_src_address() const;
    virtual void setNP_src_address(int NP_src_address);
    virtual int getNP_dest_address() const;
    virtual void setNP_dest_address(int NP_dest_address);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const N_PDU& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, N_PDU& obj) {obj.parsimUnpack(b);}


#endif // ifndef __N_PDU_M_H

